import React from 'react';
import { PublicNav, PublicFooter } from './PublicNav';
import { FileText, ShieldAlert, CheckCircle, Scale, AlertCircle } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-[#F5F5F7] text-[#1D1D1F] flex flex-col font-sans">
      <PublicNav currentPage="terms" />

      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16 space-y-10">
        {/* Header */}
        <div className="space-y-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-orange-50 border border-orange-200/60 text-[#FF4500] text-xs font-semibold">
            <span>Effective Date: October 5, 2026</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-[#1D1D1F]">
            Terms of Service
          </h1>
          <p className="text-sm text-[#6E6E73] leading-relaxed">
            These Terms of Service (&quot;Terms&quot;) govern access to and use of Apex Autonoma, provided by Apex Engineering (&quot;Company&quot;, &quot;we&quot;, &quot;our&quot;), Pune, India.
          </p>
        </div>

        {/* 1. Service Description */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">1. Service Description</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            Apex Autonoma is an AI-powered Campaign Operating System that synthesizes brand intelligence, design systems, multi-platform social media campaigns, and marketing creatives across multiple company workspaces.
          </p>
        </section>

        {/* 2. Account Responsibility & Security */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">2. Account Responsibility & Access</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            Access to Autonoma requires authentication via Google Sign-In or verified corporate credentials. You are responsible for safeguarding your login credentials and for all activities conducted under your user account and workspaces. You agree to notify Apex Engineering immediately upon becoming aware of any unauthorized use.
          </p>
        </section>

        {/* 3. Acceptable Use Policy */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">3. Acceptable Use Policy</h2>
          <div className="text-xs sm:text-sm text-[#6E6E73] space-y-2 leading-relaxed">
            <p>You agree not to use Autonoma to:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-xs text-[#6E6E73]">
              <li>Generate deceptive, defamatory, fraudulent, or unlawful marketing communications.</li>
              <li>Infringe upon any third party&apos;s trademark, copyright, privacy, or proprietary rights.</li>
              <li>Attempt to reverse-engineer, decompile, or bypass security boundaries or rate limits.</li>
              <li>Distribute malware, spam, or abusive communications across publishing channels.</li>
              <li>Circumvent multi-company workspace isolation or access data belonging to another tenant.</li>
            </ul>
          </div>
        </section>

        {/* 4. Customer Responsibility for Claims & Content */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">4. Customer Responsibility for Claims & Content</h2>
          <div className="p-4 bg-orange-50/60 rounded-xl border border-orange-200/70 text-xs text-orange-950 space-y-1.5">
            <div className="font-semibold flex items-center gap-1.5 text-orange-900">
              <AlertCircle className="w-4 h-4 text-[#FF4500]" />
              <span>Human Review & Verification Obligation</span>
            </div>
            <p className="leading-relaxed">
              The customer retains sole legal and editorial responsibility for all content, factual representations, product claims, pricing details, and compliance statements published or disseminated using materials generated by Autonoma.
            </p>
          </div>
        </section>

        {/* 5. AI Output Disclaimer */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">5. AI Output Disclaimer</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            Content, captions, images, and videos generated by third-party artificial intelligence models (including Cloudflare Workers AI FLUX, OpenAI, and Google Gemini) are probabilistic by nature and provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. Apex Engineering makes no warranties, express or implied, regarding the factual accuracy, completeness, or non-infringement of raw AI outputs without independent customer validation.
          </p>
        </section>

        {/* 6. Intellectual Property */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">6. Intellectual Property & Ownership</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            <strong>Customer Property:</strong> As between you and Apex Engineering, you retain all right, title, and interest in your pre-existing trademarks, logos, brand guidelines, and proprietary business intelligence uploaded to the platform.
          </p>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            <strong>Platform Property:</strong> Apex Engineering retains all rights, title, and interest in and to the Autonoma software, algorithms, architecture, interface designs, APIs, and documentation.
          </p>
        </section>

        {/* 7. Third-Party Providers & APIs */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">7. Third-Party Providers & APIs</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            Autonoma interfaces with third-party providers including Google (OAuth & Gemini), Cloudflare (Workers AI FLUX), OpenAI, Supabase, and Resend. Service availability may depend upon the operational status and terms of these respective third-party providers.
          </p>
        </section>

        {/* 8. Availability & Service Suspension */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">8. Availability & Suspension</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            We use commercially reasonable efforts to maintain platform availability. We reserve the right to temporarily suspend access for scheduled maintenance or immediately suspend accounts violating our Acceptable Use Policy.
          </p>
        </section>

        {/* 9. Limitation of Liability */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">9. Limitation of Liability</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            To the maximum extent permitted by applicable law, in no event shall Apex Engineering or its affiliates, directors, or employees be liable for any indirect, incidental, punitive, or consequential damages (including loss of profits, goodwill, or business interruption) arising out of or related to your use of Autonoma.
          </p>
        </section>

        {/* 10. Governing Law & Jurisdiction */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">10. Governing Law & Jurisdiction</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of <strong>India</strong>. Any disputes arising out of or relating to these Terms or the platform shall be subject to the exclusive jurisdiction of the competent courts in <strong>Pune, Maharashtra, India</strong>.
          </p>
        </section>

        {/* 11. Contact & Support */}
        <section className="bg-white rounded-2xl border border-black/[0.06] p-6 sm:p-8 space-y-3 shadow-2xs">
          <h2 className="text-base font-bold text-[#1D1D1F]">11. Contact & Support</h2>
          <p className="text-xs sm:text-sm text-[#6E6E73] leading-relaxed">
            For inquiries, notices, or support concerning these Terms, contact{' '}
            <a href="mailto:support@apex-engineering.co.in" className="text-[#FF4500] font-semibold underline">
              support@apex-engineering.co.in
            </a>
            {' '}or write to Apex Engineering, Pune, India.
          </p>
        </section>
      </main>

      <PublicFooter />
    </div>
  );
};
